config/routes.rb
Rails.application.routes.draw do

  resources :gossips
root 'gossips#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
  	render html: "hello world!"
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :set_gossip, only: [:show, :edit, :update, :destroy]

  # GET /gossips
  # GET /gossips.json
  def index
    @gossips = Gossip.all
  end

  # GET /gossips/1
  # GET /gossips/1.json
  def show
  end

  # GET /gossips/new
  def new
    @gossip = Gossip.new
  end

  # GET /gossips/1/edit
  def edit
  end

  # POST /gossips
  # POST /gossips.json
  def create
    @gossip = Gossip.new(gossip_params)

    respond_to do |format|
      if @gossip.save
        format.html { redirect_to @gossip, notice: 'Gossip was successfully created.' }
        format.json { render :show, status: :created, location: @gossip }
      else
        format.html { render :new }
        format.json { render json: @gossip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gossips/1
  # PATCH/PUT /gossips/1.json
  def update
    respond_to do |format|
      if @gossip.update(gossip_params)
        format.html { redirect_to @gossip, notice: 'Gossip was successfully updated.' }
        format.json { render :show, status: :ok, location: @gossip }
      else
        format.html { render :edit }
        format.json { render json: @gossip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gossips/1
  # DELETE /gossips/1.json
  def destroy
    @gossip.destroy
    respond_to do |format|
      format.html { redirect_to gossips_url, notice: 'Gossip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gossip
      @gossip = Gossip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gossip_params
      params.require(:gossip).permit(:anonymous_author, :content, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/_form.html.erb
<%= form_with(model: gossip, local: true) do |form| %>
  <% if gossip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gossip.errors.count, "error") %> prohibited this gossip from being saved:</h2>

      <ul>
      <% gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :anonymous_author %>
    <%= form.text_field :anonymous_author, id: :gossip_anonymous_author %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :gossip_content %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :gossip_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gossips/edit.html.erb
<h1>Editing Gossip</h1>

<%= render 'form', gossip: @gossip %>

<%= link_to 'Show', @gossip %> |
<%= link_to 'Back', gossips_path %>

app/views/gossips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gossips</h1>

<table>
  <thead>
    <tr>
      <th>Anonymous author</th>
      <th>Content</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <h3>Créer vos propres gossips, en toute sérénité! </h3>

  <tbody>
    <% @gossips.each do |gossip| %>
      <tr>
        <td><%= gossip.anonymous_author %></td>
        <td><%= gossip.content %></td>
        <td><%= gossip.title %></td>
        <td><%= link_to 'Show', gossip %></td>
        <td><%= link_to 'Edit', edit_gossip_path(gossip) %></td>
        <td><%= link_to 'Destroy', gossip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gossip', new_gossip_path %>

app/views/gossips/new.html.erb
<h1>New Gossip</h1>

<%= render 'form', gossip: @gossip %>

<%= link_to 'Back', gossips_path %>

app/views/gossips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Anonymous author:</strong>
  <%= @gossip.anonymous_author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @gossip.content %>
</p>

<p>
  <strong>Title:</strong>
  <%= @gossip.title %>
</p>

<%= link_to 'Edit', edit_gossip_path(@gossip) %> |
<%= link_to 'Back', gossips_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gossip3App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>